# Generated by Django 4.2.11 on 2026-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repartidor',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
