# Generated by Django 4.2.29 on 2026-03-20 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_cliente_rating_repartidor_rating_restaurante_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
